HAI 1.2
BTW computes 2^5
BTW cerner_2^5_2018
HOW IZ I POWERTWO YR NUM
   BOTH SAEM NUM AN 0, O RLY?
   YA RLY, FOUND YR 1
   OIC
  
   I HAS A INDEX ITZ 0
   I HAS A TOTAL ITZ 1
   IM IN YR LOOP UPPIN YR INDEX TIL BOTH SAEM INDEX AN NUM
   TOTAL R PRODUKT OF TOTAL AN 2
   IM OUTTA YR LOOP
  
   FOUND YR TOTAL
   IF U SAY SO
   VISIBLE I IZ POWERTWO YR 5 MKAY
KTHXBYE
